### PR TITLE
Fixed BLE UART data size, abstracted LPUART and formatting

### LINKED ISSUE #20: BLE UART should have data width of 8 bits
* Small issue in current BLE UART module, I defined data width as 7 bits but I think it should be 8 bits like in #19 
https://github.com/adambujak/SignBuddy/blob/51295ca2cb465096cbf745961e07d693063d0b1c/firmware/applications/SignBuddy/ble_uart.c#L28

### PR DESCRIPTION
**Pull request by stephen99scott**
* Closes #20 
* Abstract LPUART from BLE UART module
* Removed priority encoding function for consistency with LOG UART
* Fixed ADC IRQ naming to match pattern
* Added to do for BLE UART on the discovery board

### CODE REVIEW

File: firmware/applications/SignBuddy/adc.c [hunk 1]
```diff
@@ -73,7 +70,7 @@ void adc_init(void)
   while (LL_ADC_IsActiveFlag_ADRDY(ADC) == 0);
 }
 
-void ADC_IRQ_Callback(void)
+void ADC_IRQHandler(void)
```
Comment (adambujak) [inline firmware/applications/SignBuddy/adc.c:73]: nice

**Review by adambujak — APPROVED** [review]
lgtm
